### ISSUE TITLE
Add wicket-orientdb as a git submodule

### ISSUE THREAD

**Issue by krichter722** [OrienteerDW/Orienteer#133]
This wouldn't interfere with the development of `wicket-orientdb` as a separate project, but due to the fact that the projects are quite close a specific revision could be enforced if it is necessary for a patch in `Orienteer` which is not provided by the maven versioning schema x.y.z or x.y.z-SNAPSHOT.

**Comment by PhantomYdn** [comment]
I'm not so familiar with git feature for submodules. Thanks! I'll take a look.

**Comment by krichter722** [comment]
If you're ok with it I can do it.

**Comment by PhantomYdn** [comment]
Can it be delivered as PR? If yes - yes please - I will check it out.

Will it be possible, for example: make changes in this submodule and than commit them to your own wicket-orientdb clone?

**Comment by krichter722** [comment]
That is precisely the idea behind submodules. They serve to enforce a certain state of the submodule which is used for the build in the project. This state is managed in the parent git. You can commit in the submodule and no one will ever know it has be done in a submodule rather than in an independent clone, because there's no reason to distinguish.

**Comment by krichter722** [comment]
see #134

**Comment by PhantomYdn** [comment]
I see the reason... lets return to this after releasing of 1.0. While wicket-orientdb and Orienteer are being developed in parallel: imho it might slow down turn around.

**Comment by PhantomYdn** [comment]
git feature was checked. It's not for now. Issue might be reopened if some real-life cases occur.
