### ISSUE TITLE
Enhance multiple select

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerDW/Orienteer#166]
Currently: when you find some entity and click "select" - modal window will be closed.

It will be cool to have one more button (for example "Select and search more") which can allow to add already found and continue search

**Comment by evilsyncope** [comment]
Multiple select control was implemented in "Support of multi super classes" #218

**Comment by PhantomYdn** [comment]
I think that multiple select control is not suitable for this. Currently, search page has been used for searching of documents to refer to. And it's not so convinient that search window closed each time after selection. So I propose in case of multiple select to have 2 buttons: Select and Select and search
