### ISSUE TITLE
Fix internationalization

### ISSUE THREAD

**Issue by krichter722** [OrienteerDW/Orienteer#170]
Some pages of the demo show some internationalization issues, e.g. http://demo.orienteer.org/property/Clazz/prop contains both english language and word sin cyrillic characters.

**Comment by PhantomYdn** [comment]
What's your locale? It looks like a bug if you don't have 'RU' locale installed...
Btw, here http://demo.orienteer.org/browse/OLocalization you can localized application of needed.

**Comment by krichter722** [comment]
I don't how it's picked up by `firefox` 37.0 (which I'm using) or GlassFish 4.1 (which I use for my own local Orienteer instance), but I'm setting `LANG=de_DE.UTF-8` and `LC_ALL=de_DE.UTF-8` in my `~/.bashrc` (without too much knowledge about how smart that is - fixes some issues for me). Anyway, the demo shows a mixture of `EN`, `DE` and `RU`, some active, some not, see screenshot for details. My local instances don't show any cyrillic character, but display a mixture of german and english while all "Localization" properties are set to `DE`.

![localization_issue0](https://cloud.githubusercontent.com/assets/4369372/7056257/94127fe8-de4a-11e4-90b3-0b2ff71214b7.png)

![localization_issue1](https://cloud.githubusercontent.com/assets/4369372/7056256/8b599cc4-de4a-11e4-93aa-ec196d200ed5.png)

**Comment by PhantomYdn** [comment]
Thank you for the issue! It open wide range of possible localization issues. I created a couple of them to cover needs. #172 #173 
Also in 1.1 I plan to have this: #33

**Comment by PhantomYdn** [comment]
In a meanwhile: I removed russian translation from [demo server](http://demo.orienteer.org) just do not confuse visitors. Thank you again for bringing this!

**Comment by PhantomYdn** [comment]
Btw, is it really look like on your screenshots? I'm talking about top navigation bar and inplace page title (OLocalization). What browser are you using?

**Comment by krichter722** [comment]
No, that must have been the screenshot program (nimbus firefox extension), I didn't pay attention. I updated the post.

**Comment by PhantomYdn** [comment]
Formally, mentioned bug has been fixed on demo. Two remaining issues are in the roadmap.
