### ISSUE TITLE
Absolute wicket pathes don't work if deployment URL contains a path

### ISSUE THREAD

**Issue by krichter722** [OrienteerDW/Orienteer#171]
By default I'm deploying to `localhost:8080/orienteer-war` which breaks most of the `@MountPath` wicket annotations (e.g. `ListOClassesPage` is annotated with `@MountPath("/classes")`) and causes resources to be unavailable on the server.

**Comment by PhantomYdn** [comment]
Is it related only menu panel on the left?
If you navigate manually to classes pages: can you navigate then by links?

**Comment by krichter722** [comment]
All manual navigation works, all links of the menu panel on the left skip the deployment prefix.
