### ISSUE TITLE
Custom Fields Editor

### ISSUE THREAD

**Issue by deacix** [OrienteerDW/Orienteer#294]
You need to implement class property custom field editor to save settings like a grid or form configuration.

Like this:

ALTER PROPERTY MyTable.name CUSTOM kendo={
"grid": {
"height": 500
}
}

**Comment by PhantomYdn** [comment]
Thanks for the issue! Quite needed enhancement.

**Comment by PhantomYdn** [comment]
Done. Let me know if something else is expected. Demo server is updated.

**Comment by deacix** [comment]
WOW! Thanks!!
