### ISSUE TITLE
WARN:oejs.ServletHandler:/login

### ISSUE THREAD

**Issue by deacix** [OrienteerDW/Orienteer#308]
"com.orientechnologies.orient.core.exception.ODatabaseException: Database 'remote:xxx.xxx.xxx.xxx:2424/db' is closed"
If i try to login with wrong credentials to remote orientDB. Version 1.2-SNAPSHOT

**Comment by PhantomYdn** [comment]
Fixed here: https://github.com/OrienteerDW/wicket-orientdb/commit/93b3745da37545d03b3e1fd8f111259d44243a34
