### ISSUE TITLE
Widget to modify OFunction

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerDW/Orienteer#322]
The main idea: provide the same functionality to write your own functions as in OrientDB console.
So user should be able:

1) Configure function
2) Try to execute that function and see results (as plain json return) without actual saving of that function
3) Save function

Widget should work for new functions and existing in the same manner.
This widget doesn't have any configuration: it should just provide uI for function modification.

**Comment by PhantomYdn** [comment]
As it was discovered: even in OrientDB console function should be at first saved and only after that it can be executed. Because of this fact it was agreed, that we need just a widget to execute current function.

Widget should allow users to specify arguments and show results "as is".

**Comment by ankitbansal** [comment]
Direct function execution is not returning proper result. Its output is like: "{param1=10, param2=20, param3=30}undefined". Looks like REST invocation is the way to go. What do you think?

**Comment by PhantomYdn** [comment]
Yes for beginning it's ok. Please take a look to OrientDb bridge in wicket-orientdb
