### ISSUE TITLE
Add support of "default" values

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerDW/Orienteer#89]
There is new feature in OrientDB 2.1: specify default value (expression) for a property. Orienteer should support view/edit of this new "feature" of a OProperty

**Comment by PhantomYdn** [comment]
Can be done in 1.0 due to realization of the following feature in OrientDB: https://github.com/orientechnologies/orientdb/issues/665

**Comment by evilsyncope** [comment]
Should we add some validation on this field?

**Comment by PhantomYdn** [comment]
No if OrientDB doesn't have any validation of this field. 
It can contain functions, macrosses and so: so we can't count on property type to validate it.
